// Real Chromium integration tests using its DevTools Protocol and Node built-ins.
// All uploaded content is SYNTHETIC software test data. No biology or account access.
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {access,mkdir,mkdtemp,readFile,writeFile,rm,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createServer} from '../scripts/serve.mjs';
import {fixture,registry} from './helpers.mjs';
import {canonicalize,planPayload,sha256} from '../site/assets/core.js';

const repo=fileURLToPath(new URL('../',import.meta.url));
const artifacts=path.join(repo,'.test-artifacts');
await mkdir(artifacts,{recursive:true});
const explicit=process.argv.slice(2).find(arg=>!arg.startsWith('--'));
const noSandbox=process.argv.includes('--no-sandbox');
const candidates=explicit?[explicit]:process.platform==='win32'?['C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe','C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe']:['/usr/bin/chromium','/usr/bin/chromium-browser','/usr/bin/google-chrome','/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'];
let executable;
for(const candidate of candidates){try{await access(candidate);executable=candidate;break;}catch{}}
if(!executable){console.error('NOT_TESTED: no real browser found. Pass its executable path as the first argument.');process.exit(2);}
const tempBase=await realpath(tmpdir()), profile=await mkdtemp(path.join(tempBase,'genomeatlas-browser-'));
const delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn,message,timeout=10000){const start=Date.now();let last;while(Date.now()-start<timeout){try{const value=await fn();if(value)return value;}catch(error){last=error;}await delay(60);}throw new Error(`${message}${last?`: ${last.message}`:''}`);}
const server=createServer();server.listen(0,'127.0.0.1');await once(server,'listening');
const origin=`http://127.0.0.1:${server.address().port}`;
const prefixedServer=createServer(undefined,'/GenomeAtlas');prefixedServer.listen(0,'127.0.0.1');await once(prefixedServer,'listening');
const prefixedOrigin=`http://127.0.0.1:${prefixedServer.address().port}`;
const child=spawn(executable,['--headless=new',...(noSandbox?['--no-sandbox']:[]),'--disable-gpu','--remote-debugging-address=127.0.0.1','--remote-debugging-port=0',`--user-data-dir=${profile}`,'--no-first-run','--no-default-browser-check','--disable-background-networking','--disable-component-update','--disable-sync','--disable-extensions','--disable-crash-reporter','--disable-features=msEdgeSidebarV2','about:blank'],{stdio:'ignore',windowsHide:true});
let browserExit; child.on('error',e=>{browserExit=e.code;});child.on('exit',code=>{browserExit=code;});
let ws,sequence=0;const pending=new Map(),events=[];const results=[];
function call(method,params={}){return new Promise((resolve,reject)=>{const id=++sequence;const timer=setTimeout(()=>{pending.delete(id);reject(new Error(`CDP timeout: ${method}; socket state ${ws.readyState}; received ${events.length} events`));},10000);pending.set(id,{resolve,reject,timer});ws.send(JSON.stringify({id,method,params}));});}
async function evaluate(expression){const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;}
async function click(selector){const rect=await evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});if(!e)throw new Error('Element missing');e.scrollIntoView({block:'center'});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);await call('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...rect});await call('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...rect});}
async function fill(selector,value){await evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.value=${JSON.stringify(value)};e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}));})()`);}
async function upload(selector,file){const doc=await call('DOM.getDocument');const node=await call('DOM.querySelector',{nodeId:doc.root.nodeId,selector});await call('DOM.setFileInputFiles',{nodeId:node.nodeId,files:[file]});}
async function nav(view){await click(`nav a[data-view="${view}"]`);await until(()=>evaluate(`!document.getElementById('view-${view}').hidden`),`Navigation to ${view} failed`);}
async function text(id){return evaluate(`document.getElementById(${JSON.stringify(id)}).textContent`);}
async function screenshot(name){await evaluate('window.scrollTo(0,0)');await delay(250);const shot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await writeFile(path.join(artifacts,name),Buffer.from(shot.data,'base64'));}
async function run(name,fn){try{await fn();results.push({name,status:'passed'});console.log(`PASS ${name}`);}catch(error){results.push({name,status:'failed',error:error.message});console.error(`FAIL ${name}: ${error.message}`);throw error;}}
async function uploadReceipt(value,expected){const filename=path.join(artifacts,'SYNTHETIC-receipt.json');await writeFile(filename,typeof value==='string'?value:JSON.stringify(value));await evaluate("document.getElementById('import-feedback').textContent='Waiting for SYNTHETIC test import';");await upload('#receipt-file',filename);await until(async()=>new RegExp(expected,'i').test(await text('import-feedback')),`Expected import feedback ${expected}`);}
try{
  const portText=await until(async()=>{if(browserExit!==undefined)throw new Error(`Browser exited: ${browserExit}`);return readFile(path.join(profile,'DevToolsActivePort'),'utf8');},'Browser did not expose a debugging port',15000);
  const port=Number(portText.split(/\r?\n/)[0]);
  const targets=await (await fetch(`http://127.0.0.1:${port}/json/list`)).json();
  const target=targets.find(t=>t.type==='page');assert.ok(target,'Browser page target required');
  ws=new WebSocket(target.webSocketDebuggerUrl);await once(ws,'open');
  ws.addEventListener('message',event=>{const message=JSON.parse(event.data);if(message.id){const item=pending.get(message.id);if(item){clearTimeout(item.timer);pending.delete(message.id);if(message.error)item.reject(new Error(`${message.error.code}: ${message.error.message}`));else item.resolve(message.result);}}else events.push(message);});
  const version=await call('Browser.getVersion');console.log(`Browser: ${version.product}`);
  await call('Page.enable');await call('Runtime.enable');await call('Network.enable');
  await call('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:artifacts});
  await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1080,deviceScaleFactor:1,mobile:false});
  await call('Page.navigate',{url:origin});
  await until(()=>evaluate("document.documentElement.dataset.ready==='true'"),'App did not initialize');
  await until(()=>evaluate("!document.getElementById('test-summary').textContent.includes('Loading')"),'Report did not load');

  await run('desktop overview, inherited scope, publication boundary and screenshot',async()=>{
    assert.equal(await evaluate("document.querySelector('h1').textContent"),'Workspace overview');
    assert.match(await text('view-overview'),/177/);assert.match(await text('view-overview'),/No Enterococcus/);assert.match(await text('view-overview'),/PUBLICATION BLOCKED BY TASK/);
    assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);await screenshot('overview-desktop.png');
  });
  await run('five-view navigation and browser history',async()=>{for(const id of ['tools','chains','evidence','delegation','overview'])await nav(id);await evaluate('history.back()');await until(()=>evaluate("location.hash==='#delegation'"),'Back navigation failed');});
  await run('tool search, category, probe filtering and empty state',async()=>{await nav('tools');assert.equal(await evaluate("document.querySelectorAll('.tool-card').length"),registry.tools.length);await fill('#tool-search','SYNTHETIC-NO-MATCH');assert.equal(await evaluate("document.getElementById('tool-empty').hidden"),false);await click('#reset-filters');await fill('#tool-group','Biology');assert.ok((await evaluate("document.querySelectorAll('.tool-card').length"))>0);await fill('#tool-probe','passed');assert.equal(await evaluate("document.querySelectorAll('.tool-card').length"),registry.tools.filter(t=>t.group==='Biology'&&t.probe==='passed').length);await click('#reset-filters');await fill('#tool-search','smarts');assert.equal(await evaluate("document.querySelectorAll('.tool-card').length"),1);});
  await run('source inspection opens attributed detail and Escape closes dialog',async()=>{await click('.tool-card button');assert.match(await text('inspector-body'),/checksum|404/);assert.match(await text('inspector-body'),/Parent-supplied integration limits/);await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});assert.equal(await evaluate("document.getElementById('inspector').open"),false);});
  await run('JSON and CSV tool downloads reflect active filter',async()=>{for(const [id,name] of [['export-tools-json','genomeatlas-tools.json'],['export-tools-csv','genomeatlas-tools.csv']]){await rm(path.join(artifacts,name),{force:true});await click('#'+id);await until(()=>readFile(path.join(artifacts,name),'utf8'),'Download missing');}const json=JSON.parse(await readFile(path.join(artifacts,'genomeatlas-tools.json'),'utf8'));assert.equal(json.tools.length,1);assert.equal(json.tools[0].id,'smarts');assert.match(await readFile(path.join(artifacts,'genomeatlas-tools.csv'),'utf8'),/scientificAcceptance/);await click('#reset-filters');await screenshot('tools-desktop.png');});
  await run('SVG workflow selection and keyboard activation',async()=>{await nav('chains');await click('[data-stage="review"]');assert.match(await text('stage-detail'),/Manual locus review/);await evaluate("document.querySelector('[data-stage=alignments]').focus()");await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13});assert.match(await text('stage-detail'),/Independent alignments/);await screenshot('chains-desktop.png');});
  await run('receipt empty state and malformed JSON rejection',async()=>{await nav('evidence');assert.equal(await evaluate("document.getElementById('receipt-empty').hidden"),false);await uploadReceipt('{broken','Malformed JSON');assert.equal(await text('receipt-count'),'0');});
  for(const [label,mutate,expected] of [
    ['unknown stage',async r=>{r.stageId=r.plan.stageId='unknown-stage';r.plan.planHash=await sha256(canonicalize(planPayload(r.plan)));r.planHash=r.plan.planHash;},'Unknown stage'],
    ['unknown tool',async r=>{r.toolId=r.plan.toolId='unknown-tool';r.plan.planHash=await sha256(canonicalize(planPayload(r.plan)));r.planHash=r.plan.planHash;},'Unknown tool'],
    ['missing hashes',async r=>{delete r.planHash;},'required'],
    ['unsupported verified claim',async r=>{r.evidenceStatus='verified';},'must equal'],
    ['unsupported scientific acceptance',async r=>{r.scientificAcceptance='accepted';},'must equal']
  ])await run(`receipt negative: ${label}`,async()=>{const r=await fixture();await mutate(r);await uploadReceipt(r,expected);assert.equal(await text('receipt-count'),'0');});
  await run('HTML injection is literal text; no element, code execution or URL request',async()=>{const r=await fixture();r.receiptId='SYNTHETIC-XSS';r.claimedOutcome='succeeded';r.notes='<img src="https://invalid.example/SYNTHETIC" onerror="globalThis.pwned=1"><script>globalThis.pwned=2</script>';await uploadReceipt(r,'Imported as UNVERIFIED');assert.equal(await text('receipt-count'),'1');assert.equal(await evaluate("document.querySelectorAll('#receipt-list img, #receipt-list script').length"),0);assert.equal(await evaluate('globalThis.pwned||0'),0);assert.match(await text('receipt-list'),/<img src=/);assert.match(await text('receipt-list'),/Claimed outcome: succeeded/);assert.match(await text('receipt-list'),/not assessed/);assert.equal(events.some(e=>e.method==='Network.requestWillBeSent'&&e.params.request.url.includes('invalid.example')),false);await uploadReceipt(r,'Duplicate');});
  await run('receipt export retains unverified status and safely quotes CSV',async()=>{for(const [id,name] of [['export-receipts-json','genomeatlas-claims.json'],['export-receipts-csv','genomeatlas-claims.csv']]){await rm(path.join(artifacts,name),{force:true});await click('#'+id);await until(()=>readFile(path.join(artifacts,name),'utf8'),'Receipt download missing');}const data=JSON.parse(await readFile(path.join(artifacts,'genomeatlas-claims.json'),'utf8'));assert.equal(data.claims[0].evidenceStatus,'unverified');assert.match(await readFile(path.join(artifacts,'genomeatlas-claims.csv'),'utf8'),/unverified/);await click('#clear-receipts');assert.equal(await text('receipt-count'),'0');await screenshot('evidence-desktop.png');});
  let builtPlan;
  await run('real file hashing, plan generation and local checklist',async()=>{await nav('delegation');await fill('#plan-purpose','SYNTHETIC browser test plan. No biology.');await fill('#plan-parameters','SYNTHETIC no-op; never execute.');const input=path.join(artifacts,'SYNTHETIC-manifest.txt');await writeFile(input,'SYNTHETIC TEST INPUT ONLY\n');await upload('#plan-files',input);await click('#build-plan');await until(async()=>/Plan prepared/.test(await text('plan-feedback')),'Plan build failed');builtPlan=JSON.parse(await text('plan-json'));assert.equal(builtPlan.inputs[0].sha256,await sha256('SYNTHETIC TEST INPUT ONLY\n'));assert.equal(await evaluate("document.getElementById('export-review').disabled"),true);for(const key of ['scope','inputs','method','resources','privacy','reviewer'])await click(`[data-check="${key}"]`);assert.match(await text('review-status'),/6 of 6 locally reviewed/);assert.match(await text('review-status'),/nothing will execute/);});
  await run('plan, template and review download hash bindings',async()=>{for(const [id,name] of [['export-plan','genomeatlas-plan.json'],['export-template','genomeatlas-receipt-template.json'],['export-review','genomeatlas-local-review.json']]){await rm(path.join(artifacts,name),{force:true});await click('#'+id);await until(()=>readFile(path.join(artifacts,name),'utf8'),'Plan artifact download missing');}const p=JSON.parse(await readFile(path.join(artifacts,'genomeatlas-plan.json'),'utf8')),r=JSON.parse(await readFile(path.join(artifacts,'genomeatlas-receipt-template.json'),'utf8')),v=JSON.parse(await readFile(path.join(artifacts,'genomeatlas-local-review.json'),'utf8'));assert.equal(r.planHash,p.planHash);assert.equal(r.claimedOutcome,'not-run');assert.equal(v.planHash,p.planHash);assert.equal(v.executionAuthority,false);});
  await run('matching template can import but remains unverified',async()=>{await nav('evidence');await uploadReceipt(await readFile(path.join(artifacts,'genomeatlas-receipt-template.json'),'utf8'),'Imported as UNVERIFIED');assert.equal(await text('receipt-count'),'1');await click('#clear-receipts');});
  await run('input change clears review; changed-input receipt reuse rejected',async()=>{await nav('delegation');await fill('#plan-parameters','SYNTHETIC changed method');assert.equal(await evaluate("document.getElementById('export-review').disabled"),true);assert.equal(await evaluate("document.querySelectorAll('[data-check]:checked').length"),0);await click('#build-plan');await until(async()=>/Plan prepared/.test(await text('plan-feedback')),'Rebuild failed');assert.notEqual(JSON.parse(await text('plan-json')).planHash,builtPlan.planHash);await nav('evidence');await uploadReceipt(await readFile(path.join(artifacts,'genomeatlas-receipt-template.json'),'utf8'),'Changed-input reuse blocked');assert.equal(await text('receipt-count'),'0');await nav('delegation');await click('#clear-plan');});
  await run('mobile navigation, no page overflow, readable controls and actual screenshot',async()=>{await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});for(const view of ['overview','tools','chains','evidence','delegation']){await nav(view);assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true,`${view} overflow`);}await nav('overview');await screenshot('overview-mobile.png');await nav('delegation');await screenshot('delegation-mobile.png');});
  await run('tablet layout and fresh empty state on reload',async()=>{await call('Emulation.setDeviceMetricsOverride',{width:820,height:1180,deviceScaleFactor:1,mobile:false});await call('Page.reload',{ignoreCache:true});await until(()=>evaluate("document.documentElement.dataset.ready==='true'"),'Reload failed');assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);assert.equal(await text('receipt-count'),'0');assert.equal(await evaluate("document.getElementById('review-checklist').disabled"),true);});
  await run('registry network failure shows helpful error and retry recovers',async()=>{await call('Network.setBlockedURLs',{urls:['*data/registry.json*']});await call('Page.reload',{ignoreCache:true});await until(()=>evaluate("document.documentElement.dataset.ready==='error'"),'Missing registry error absent');assert.equal(await evaluate("document.getElementById('boot-error').hidden"),false);assert.match(await text('boot-error-message'),/HTTP|fetch/i);await call('Network.setBlockedURLs',{urls:[]});await click('#retry-load');await until(()=>evaluate("document.documentElement.dataset.ready==='true'"),'Retry failed');});
  await run('GitHub Pages style subdirectory serves all views and relative assets',async()=>{await call('Page.navigate',{url:prefixedOrigin+'/GenomeAtlas'});await until(()=>evaluate("document.documentElement.dataset.ready==='true' && location.pathname==='/GenomeAtlas/'"),'Subdirectory initialization failed');for(const view of ['overview','tools','chains','evidence','delegation'])await nav(view);assert.equal(await evaluate("document.querySelectorAll('.tool-card').length"),registry.tools.length);});
  await run('normal app requests stay local and no uncaught JavaScript errors',async()=>{assert.equal(events.filter(e=>e.method==='Runtime.exceptionThrown').length,0);const external=events.filter(e=>e.method==='Network.requestWillBeSent').map(e=>e.params.request.url).filter(url=>!url.startsWith(origin)&&!url.startsWith(prefixedOrigin)&&!url.startsWith('data:')&&!url.startsWith('blob:'));assert.deepEqual(external,[]);});
  await writeFile(path.join(artifacts,'browser-results.json'),JSON.stringify({status:'PASSED',browser:version.product,noSandbox,syntheticData:true,checks:results},null,2));
  console.log(`${results.length} browser checks passed. Screenshots are actual browser captures in .test-artifacts/.`);
}catch(error){
  console.error(error.message);process.exitCode=1;
  await writeFile(path.join(artifacts,'browser-results.json'),JSON.stringify({status:'FAILED',syntheticData:true,checks:results,error:error.message},null,2));
}finally{
  for(const item of pending.values()){clearTimeout(item.timer);item.reject(new Error('Browser test closing'));}pending.clear();
  if(ws)ws.close();child.kill();server.closeAllConnections();server.close();prefixedServer.closeAllConnections();prefixedServer.close();
  // Verify this is exactly the task-created directory under the system temp root before recursive removal.
  const resolved=path.resolve(profile);if(path.dirname(resolved)===tempBase && path.basename(resolved).startsWith('genomeatlas-browser-')){
    await delay(300);try{await rm(resolved,{recursive:true,force:true,maxRetries:4,retryDelay:200});}catch{console.error('Temporary browser profile cleanup incomplete; no account profile was used.');}
  }
}
