const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const C=require('../docs/contracts.js');
const template=JSON.parse(fs.readFileSync('docs/templates/review-request.json','utf8'));
const request=()=>({...structuredClone(template),reviewer:'reviewer',requested_endpoint:'workspace'});
const receipt=()=>({schema_version:1,kind:'RUN_RECEIPT',job:'panel-audit',claimed_status:'PASSED',summary:'Claim only',evidence_reference:'public-evidence'});
test('valid request and import',()=>assert.deepEqual(C.parseImport(JSON.stringify(request())),request()));
test('missing inputs rejected',()=>{const r=request();r.input_hashes=[];assert.ok(C.validateRequest(r).length)});
test('duplicate input rejected',()=>{const r=request();r.input_hashes.push(r.input_hashes[0]);assert.ok(C.validateRequest(r).length)});
test('consent is not execution',()=>{const r=request();r.state='REQUIRES_CONFIRMATION';assert.equal(C.validateRequest(r).length,0);r.execution='EXECUTED';assert.ok(C.validateRequest(r).length)});
test('approval and receipt cannot enter request',()=>{const r=request();r.state='APPROVED';r.run_receipt={};assert.ok(C.validateRequest(r).length)});
test('malformed imports rejected',()=>{for(const raw of ['{','null','[]','1','"text"']){assert.throws(()=>C.parseImport(raw));assert.throws(()=>C.parseReceipt(raw))}});
test('oversize UTF8 rejected',()=>{assert.throws(()=>C.parseReceipt('é'.repeat(32769)));assert.throws(()=>C.parseImport(' '.repeat(65537)))});
test('receipt stays untrusted even if claim passed',()=>{const r=C.parseReceipt(JSON.stringify(receipt()));assert.equal(r.verified,false);assert.equal(r.trust,'UNTRUSTED_IMPORT')});
test('receipt unknown fields and false verification rejected',()=>{for(const extra of [{verified:true},{call:'P'},{__extra:1}])assert.throws(()=>C.parseReceipt(JSON.stringify({...receipt(),...extra})))});
test('receipt invalid status and text rejected',()=>{for(const extra of [{claimed_status:'VERIFIED'},{summary:''},{summary:[]},{summary:'a'.repeat(2001)}])assert.throws(()=>C.parseReceipt(JSON.stringify({...receipt(),...extra})))});
test('markup retained as literal text for inert rendering',()=>{const r=receipt();r.summary='<img src=x onerror=alert(1)>';assert.equal(C.parseReceipt(JSON.stringify(r)).summary,r.summary);assert.ok(!/innerHTML|insertAdjacentHTML/.test(fs.readFileSync('docs/app.js','utf8')))});
test('failed is not absent',()=>assert.equal(C.scientificState({job_status:'FAILED',call:'ABSENT',assessment_complete:true,exact_strain_evidence:true,evidence_reference:'x'}),'FAILED'));
test('unknown missing or not tested is not absent',()=>{for(const s of [undefined,'UNKNOWN','NOT_TESTED','BLOCKED'])assert.equal(C.scientificState({job_status:s,call:'ABSENT'}),'NA')});
test('raw hit remains U and cassette is not proof',()=>assert.equal(C.scientificState({job_status:'PASSED',call:'P',complete_cassette:true}),'U'));
test('curated P needs exact strain evidence',()=>{assert.equal(C.scientificState({job_status:'PASSED',call:'P',curated:true}),'U');assert.equal(C.scientificState({job_status:'PASSED',call:'P',curated:true,exact_strain_evidence:true,evidence_reference:'reviewed-record'}),'P')});
test('absence requires complete exact strain assessment',()=>{assert.equal(C.scientificState({job_status:'PASSED',call:'ABSENT'}),'NA');assert.equal(C.scientificState({job_status:'PASSED',call:'ABSENT',assessment_complete:true,exact_strain_evidence:true,evidence_reference:'reviewed-record'}),'0')});
test('state vocabulary and duplicate tool IDs',()=>{const d=JSON.parse(fs.readFileSync('docs/data/atlas.json'));assert.deepEqual(d.states,C.STATES);assert.equal(new Set(d.tools.map(t=>t.id)).size,d.tools.length)});
test('unallowed job and negative budget rejected',()=>{const r=request();r.job='gpu-run';r.budget_cap.amount=-1;assert.ok(C.validateRequest(r).length>=2)});
