import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {INVARIANTS,DIMENSIONS,STATES,MAX_BYTES,validateScience,validateDocument,validateAccessions,parseImport,parseParentSnapshot,exportImport,makeJob,serializeJob} from '../docs/core.mjs';
const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8');
const registry=JSON.parse(read('docs/data/registry.json'));
const probe=JSON.parse(read('docs/data/import-example.json'));
const copy=x=>structuredClone(x);
const mutate=(x,fn)=>{const clone=copy(x);fn(clone);return clone;};
test('bundled registry has a valid schema and all required tools',()=>{assert.equal(validateDocument(registry),registry);assert.equal(registry.records.length,89);for(const id of ['rdc','github','codex','wsl','datasets','gtotree','hmmer','mafft','trimal','iqtree','defensefinder','rebase','literature','geneious','bionemo','smarts','alphagenome','sites'])assert.ok(registry.records.find(r=>r.id===id));});
test('all state values accepted without conflating dimensions',()=>{for(const state of STATES){const doc=copy(registry);doc.records[0].states.executed=state;assert.doesNotThrow(()=>validateDocument(doc));}assert.equal(DIMENSIONS.length,5);});
test('invalid registry state rejected',()=>assert.throws(()=>validateDocument(mutate(registry,d=>d.records[0].states.executed='ready'))));
test('unknown field rejected',()=>assert.throws(()=>validateDocument({...registry,verified:true})));
test('missing field rejected',()=>assert.throws(()=>validateDocument(mutate(registry,d=>delete d.records[0].notes))));
test('duplicate tool rejected',()=>assert.throws(()=>validateDocument(mutate(registry,d=>d.records.push(d.records[0])))));
test('empty registry rejected',()=>assert.throws(()=>validateDocument({...registry,records:[]})));
test('oversized registry rejected',()=>assert.throws(()=>validateDocument({...registry,records:Array(101).fill(registry.records[0])})));
test('positive state needs evidence ID',()=>assert.throws(()=>validateDocument(mutate(registry,d=>d.records[0].evidenceIds=[]))));
test('unsupported schema rejected',()=>assert.throws(()=>validateDocument({...probe,schemaVersion:2})));
test('valid probe schema',()=>assert.equal(validateDocument(probe),probe));
test('invalid probe state rejected',()=>assert.throws(()=>validateDocument(mutate(probe,d=>d.records[0].state='complete'))));
test('invalid probe dimension rejected',()=>assert.throws(()=>validateDocument(mutate(probe,d=>d.records[0].dimension='verified'))));
test('invalid and impossible timestamps rejected',()=>{for(const time of ['yesterday','2026-02-30T12:00:00Z'])assert.throws(()=>validateDocument(mutate(probe,d=>d.records[0].observedAt=time)));});
test('duplicate probe IDs rejected',()=>assert.throws(()=>validateDocument({...probe,records:[probe.records[0],probe.records[0]]})));
test('scientific design positive',()=>assert.equal(validateScience({...INVARIANTS}).genomes,177));
test('bundled science contract matches frozen design',()=>assert.deepEqual(validateScience(JSON.parse(read('docs/data/science.json'))),INVARIANTS));
for(const key of Object.keys(INVARIANTS))test('scientific invariant rejects change: '+key,()=>assert.throws(()=>validateScience({...INVARIANTS,[key]:typeof INVARIANTS[key]==='boolean'?!INVARIANTS[key]:'wrong'})));
test('frozen accessions exactly 177 unique versioned RefSeq IDs',()=>assert.equal(validateAccessions(read('docs/sources/selected_accessions_stage1.txt'),true).length,177));
test('valid small accession input',()=>assert.deepEqual(validateAccessions('GCF_000123456.1\r\n'),['GCF_000123456.1']));
test('empty accessions rejected',()=>{for(const input of ['', '  ', '\n'])assert.throws(()=>validateAccessions(input));});
test('duplicate accessions rejected',()=>assert.throws(()=>validateAccessions('GCF_000123456.1\nGCF_000123456.1')));
test('blank inner accession rejected',()=>assert.throws(()=>validateAccessions('GCF_000123456.1\n\nGCF_000123457.1')));
test('unversioned and GenBank IDs rejected',()=>{for(const input of ['GCF_000123456','GCA_000123456.1'])assert.throws(()=>validateAccessions(input));});
test('wrong frozen panel size rejected',()=>assert.throws(()=>validateAccessions('GCF_000123456.1',true)));
test('malformed JSON rejected',()=>assert.throws(()=>parseImport('{')));
test('nonobject JSON rejected',()=>{for(const raw of ['null','[]','1','"hello"'])assert.throws(()=>parseImport(raw));});
test('oversized bytes rejected including multibyte text',()=>{assert.throws(()=>parseImport(' '.repeat(MAX_BYTES+1)));assert.throws(()=>parseImport('Ж'.repeat(MAX_BYTES)));});
for(const payload of ['<img src=x onerror=alert(1)>','<script>alert(1)</script>','javascript:alert(1)','&#60;script&#62;','&lt;svg&gt;','\u202eexe'])test('reject unsafe imported text '+JSON.stringify(payload),()=>assert.throws(()=>parseImport(JSON.stringify(mutate(probe,d=>d.records[0].summary=payload)))));
test('prototype and verification fields rejected',()=>{assert.throws(()=>parseImport('{"schemaVersion":1,"kind":"probes","records":[],"__proto__":{}}'));assert.throws(()=>parseImport(JSON.stringify({...probe,verified:true})));});
test('false-result promotion impossible via valid positive claims',()=>{const prior=JSON.stringify(registry);const supplied=parseImport(JSON.stringify(mutate(probe,d=>d.records[0].state='yes')));assert.equal(supplied.verified,false);assert.equal(supplied.origin,'user-supplied');assert.equal(JSON.stringify(registry),prior);});
test('claim export retains provenance and exact content',()=>{const imported=parseImport(JSON.stringify(probe));assert.deepEqual(JSON.parse(exportImport(imported)),imported);assert.equal(JSON.parse(exportImport(imported)).verified,false);});
test('claim export rejects verified tampering',()=>assert.throws(()=>exportImport({...parseImport(JSON.stringify(probe)),verified:true})));
const fields={task:'Review bounded pilot',inputs:'Frozen accession IDs and hashes',expectedOutputs:'Inventory and receipt',testGate:'Reject duplicates',permissionBoundary:'No execution, GPU, downloads or costs authorized',reviewerDecision:'pending'};
test('job contains review fields and receipt requirements',()=>{const job=makeJob(fields);assert.equal(job.certified,false);assert.equal(job.executionStatus,'not-executed');assert.ok(job.receiptSchema.required.includes('inputHashes'));assert.deepEqual(JSON.parse(serializeJob(job)),job);});
test('approved request remains unexecuted and uncertified',()=>{const job=makeJob({...fields,reviewerDecision:'approved'});assert.equal(job.certified,false);assert.equal(job.executionStatus,'not-executed');});
test('missing job boundary rejected',()=>{const changed={...fields};delete changed.permissionBoundary;assert.throws(()=>makeJob(changed));});
test('invalid decision rejected',()=>assert.throws(()=>makeJob({...fields,reviewerDecision:'executed'})));
test('unsafe job markup rejected',()=>assert.throws(()=>makeJob({...fields,inputs:'<iframe>'})));
test('job export rejects changed execution status',()=>assert.throws(()=>serializeJob({...makeJob(fields),executionStatus:'executed'})));
test('job export rejects forged receipt',()=>assert.throws(()=>serializeJob({...makeJob(fields),receipt:{exitCode:0}})));
const parent={schema_version:'1.0',observed_at:'2026-09-09T14:41:00Z',scope:'readiness, not biological results',probes:[{id:'codex',tool:'Codex',status:'RUNNING',session_id:'00000000-0000-0000-0000-000000000000',result:'Synthetic test fixture, not an actual observation.'}],scientific_state:{panel:'177 identifiers',host_tree:'NOT_RUN',rm_calls:'NOT_RUN',experimental_curation:'NOT_RUN'}};
test('parent adapter accepts BOM and strips private session reference',()=>{const result=parseParentSnapshot('\uFEFF'+JSON.stringify(parent));assert.equal(result.records[0].state,'yes');assert.equal(result.records[0].dimension,'probed');assert.ok(!JSON.stringify(result).includes('00000000-'));});
test('parent adapter rejects invalid states',()=>assert.throws(()=>parseParentSnapshot(JSON.stringify(mutate(parent,d=>d.probes[0].status='VERIFIED')))));
test('parent adapter rejects injected markup',()=>assert.throws(()=>parseParentSnapshot(JSON.stringify(mutate(parent,d=>d.probes[0].result='<script>')))));
test('parent adapter rejects biological-result promotion',()=>assert.throws(()=>parseParentSnapshot(JSON.stringify(mutate(parent,d=>d.scientific_state.host_tree='COMPLETE')))));
test('parent adapter rejects unexpected fields',()=>assert.throws(()=>parseParentSnapshot(JSON.stringify(mutate(parent,d=>d.probes[0].token='not-a-token')))));
test('parent adapter rejects duplicate IDs and bad hashes',()=>{assert.throws(()=>parseParentSnapshot(JSON.stringify(mutate(parent,d=>d.probes.push(d.probes[0])))));assert.throws(()=>parseParentSnapshot(JSON.stringify(mutate(parent,d=>d.probes[0].sha256='bad'))));});
test('parent adapter rejects oversized input',()=>assert.throws(()=>parseParentSnapshot(' '.repeat(MAX_BYTES+1))));

test('cached plugin entries do not imply enabled/authenticated/runtime readiness',()=>{const rows=registry.records.filter(r=>r.id.startsWith('cached-'));assert.equal(rows.length,71);for(const r of rows){assert.equal(r.states.exposed,'unknown');assert.equal(r.states.authenticated,'unknown');assert.equal(r.states.executed,'not-tested');assert.ok(r.notes.includes('cached files only'));}});
