"""Bundle the public JSON as a classic script so the site also opens via file://."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def bundle():
    data = json.loads((ROOT / "docs/data/atlas.json").read_text(encoding="utf-8"))
    return "// Generated by scripts/build_data.py; edit docs/data/atlas.json.\nwindow.ATLAS_DATA = " + json.dumps(data, ensure_ascii=True, indent=2) + ";\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "docs/data.js"
    expected = bundle()
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != expected:
            raise SystemExit("FAIL: data.js is stale; run python scripts/build_data.py")
        print("PASS: public JSON and file-compatible bundle match")
    else:
        target.write_text(expected, encoding="utf-8", newline="\n")
        print("Wrote docs/data.js")
