"""Build allowlisted static assets. No biology, network, shell or deployment."""
from pathlib import Path
import hashlib
import json
import re
import shutil

ROOT = Path(__file__).resolve().parents[1]
DATA_FILES = ['registry.json', 'panel.json', 'chains.json', 'probes.json', 'selected_accessions.txt', 'live_probes.json']
PUBLIC_FILES = ['index.html', 'assets/styles.css', 'assets/app.mjs', 'assets/core.mjs',
                'assets/mark.svg', 'assets/data.mjs', 'LICENSE', 'THIRD_PARTY_NOTICES.md',
                'schemas/task-request.schema.json', 'schemas/probe-result.schema.json',
                'templates/task-request.json', 'templates/probe-result.synthetic.json',
                'templates/reproducible-config.json'] + ['data/' + name for name in DATA_FILES]


def read_json(name):
    return json.loads((ROOT / name).read_text(encoding='utf-8-sig'))


def load_snapshot():
    panel = read_json('data/panel.json')
    ids = [row['accession'] for row in panel]
    selected = (ROOT / 'data/selected_accessions.txt').read_text(encoding='utf-8-sig').splitlines()
    if len(ids) != 177 or len(set(ids)) != len(ids) or ids != selected:
        raise ValueError('Frozen accession count, uniqueness or ordered text/JSON parity failed')
    if not all(re.fullmatch(r'GCF_[0-9]{9}\.[1-9][0-9]*', accession) for accession in ids):
        raise ValueError('Invalid versioned accession')
    if any(set(row) != {'accession', 'metadata_status', 'source'} or row['metadata_status'] != 'NOT_REFRESHED' for row in panel):
        raise ValueError('Frozen metadata contract changed; no inferred taxonomy allowed')
    chains = read_json('data/chains.json')
    if [row['id'] for row in chains] != ['panel', 'download', 'markers', 'tree', 'rm', 'evidence', 'figure', 'release']:
        raise ValueError('Unexpected chain set or order')
    if any(row['status'] != 'PROPOSED_NOT_EXECUTED' for row in chains):
        raise ValueError('Analysis receipt review required before changing chain status')
    registry = read_json('data/registry.json')
    if len({row['id'] for row in registry['entries']}) != len(registry['entries']):
        raise ValueError('Duplicate registry IDs')
    manifest = {f'data/{name}': hashlib.sha256((ROOT / 'data' / name).read_bytes()).hexdigest() for name in DATA_FILES}
    return {'live':read_json('data/live_probes.json'), 'registry':registry, 'panel':panel, 'chains':chains, 'probes':read_json('data/probes.json'),
            'native':read_json('evidence/native-tools.json'), 'manifest':manifest,
            'schemas':{'task':read_json('schemas/task-request.schema.json'), 'probe':read_json('schemas/probe-result.schema.json')}}


def build():
    snapshot = load_snapshot()
    bundle = '// Generated by scripts/build.py from unchanged repository JSON. MIT code; source data provenance retained.\nexport default ' + json.dumps(snapshot, ensure_ascii=True, separators=(',', ':')) + ';\n'
    (ROOT / 'assets/data.mjs').write_text(bundle, encoding='utf-8', newline='\n')
    dist = ROOT / 'dist'
    if dist.is_symlink() or not dist.resolve().is_relative_to(ROOT):
        raise ValueError('Output must remain inside this repository')
    dist.mkdir(exist_ok=True)
    expected = set(PUBLIC_FILES + ['manifest.json'])
    # Never recursively remove an output directory: refuse unrelated artifacts.
    if any(file.is_file() and file.relative_to(dist).as_posix() not in expected for file in dist.rglob('*')):
        raise ValueError('Unexpected existing dist file; refusing to overwrite unrelated work')
    for name in PUBLIC_FILES:
        destination = dist / name
        if destination.is_symlink() or not destination.resolve().is_relative_to(dist.resolve()):
            raise ValueError('Unsafe output path')
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(ROOT / name, destination)
    manifest = {name:hashlib.sha256((dist / name).read_bytes()).hexdigest() for name in PUBLIC_FILES}
    (dist / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n', encoding='utf-8')
    print(f'Built {len(PUBLIC_FILES)} static files + manifest.json into dist/')
    print(f'Source data: {len(snapshot["panel"])} frozen genomes, {len(snapshot["registry"]["entries"])} registry entries, {len(snapshot["chains"])} proposed chains')
    print('No execution, inference, metadata refresh or deployment performed.')


if __name__ == '__main__':
    build()
